[package]
name = "plotly"
version = "0.5.0"
description = "A plotting library powered by Plotly.js"
authors = ["Ioannis Giagkiozis <i.giagkiozis@gmail.com>"]
license = "MIT"
workspace = ".."
readme = "README.md"
homepage = "https://github.com/igiagkiozis/plotly"
documentation = "https://docs.rs/plotly"
repository = "https://github.com/igiagkiozis/plotly"
edition = "2018"
keywords = ["plot", "chart", "plotly"]

exclude = [
    "target/*"
]

[features]
# Adds plot save functionality to the following formats: png, jpeg, webp, svg, pdf and eps.
orca = ["plotly_orca"]
kaleido = ["plotly_kaleido"]
ndarray = ["plotly_ndarray"]

[dependencies]
plotly_orca = { version = "0.2.1", path = "../plotly_orca", optional = true }
plotly_kaleido = { version = "0.1.0", path = "../plotly_kaleido", optional = true }
plotly_ndarray = { version = "0.1.0", path = "../plotly_ndarray", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
askama = "0.9.0"
rand = "0.7.3"
rand_distr = "0.2.2"
num = "0.2.1"

[dev-dependencies]
plotly_orca = { version = "0.2.1", path = "../plotly_orca" }
plotly_kaleido = { version = "0.1.0", path = "../plotly_kaleido" }
plotly_ndarray = { version = "0.1.0", path = "../plotly_ndarray" }
